### ISSUE TITLE
ECDSA private key not encrypted

### ISSUE THREAD

**Issue by littleskunk** [Storj/core-cli#15]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj --version
1.0.1
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
.storj-cli/id_ecdsa should be encrypted like .storjshare/id_ecdsa
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
.storj-cli/id_ecdsa is unencrypted. On a multiuser system this is a security risk.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

**Comment by aleitner** [comment]
If we encrypt this you'll have to hav an ecnryption password in addition to your keyring password every time you do something. That's no feasible

**Comment by littleskunk** [comment]
http://docs.storj.io/#4-pairing-a-device-with-your-account
```
Passwords suck so we like to avoid them when we can. Behind the scenes, we use super secure ECDSA keys that would take a computer the size of the sun to crack (provided you keep your keys safe).
```

And at the end we store the super secure key unencrypted on a linux or windows multi user system? Doesn't make sense. I understand that I would be forced to enter the key every time or set an env variable but that is better than an unprotected key.

Think about this long term. Even if we define storj-cli as a test tool for developers it is a security risk. I could install the most secure storj GUI and lose all files with a simple `storj login` that will give everyone full access to my account.

**Comment by bookchin** [comment]
@aleitner if we encrypted the key with the same passphrase and the keyring, this might not be too bad UX wise. I would just hate to confuse the user with 3 separate passphrases: account, keyring, and ecdsa key.
