### ISSUE TITLE
Logged into multiple bridges at once

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core-cli#23]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@1.0.1 /home/gordon/Code/storj-bridge
└── storj@4.0.1  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

```
I can be logged into only one bridge at a time.
```

### Actual Behavior

```
C:\Users\Dani Marion>storj login
 [Mon Oct 10 2016 22:08:02 GMT+0200 (W. Europe Daylight Time)] [error]  This device is already paired.

C:\Users\Dani Marion>storj --url http://apipool001.storj.dk login
 [Mon Oct 10 2016 22:08:14 GMT+0200 (W. Europe Daylight Time)] [error]  This device is already paired.

C:\Users\Dani Marion>

```

### Steps to Reproduce

Login once to both bridges

**Comment by littleskunk** [comment]
Feature request. Storj-cli is not designed to work with multiple bridges at the same time.

**Comment by littleskunk** [comment]
Workaround: `storj logout` to delete the local key and than `storj --url http://apipool001.storj.dk login` will work correct.

**Comment by MeijeSibbel** [comment]
I can confirm, that workaround works, thanks @littleskunk !
