### ISSUE TITLE
Bridge change in code (index.js) has no effect, it still uses the api.storj.io in command line

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core-cli#24]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@1.0.1/home/gordon/Code/storj-bridge
└── storj@4.0.1  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Using:

```
BridgeClient.prototype._checkOptions = function(uri, options) {
  options = merge({
    baseURI: uri || process.env.STORJ_BRIDGE || 'https://apipool001.storj.dk',
    logger: new Logger(0),
    transferConcurrency: 6,
    transferRetries: 0,
    blacklistFolder: utils.tmpdir(),
    requestTimeout: 20000
  }, options);

  assert.ok(utils.validateLogger(options.logger), 'Invalid logger supplied');

  return options;
};
```

then using, ```storj list-buckets``` should return buckets for bridge, https://apipool001.storj.dk , yet it still returns buckets for api.storj.io

### Actual Behavior

```
Returns buckets for apipool001.storj.dk instead of buckets for api.storj.io
```

### Steps to Reproduce

Change bridge client in C:\Users\Dani Marion\AppData\Roaming\npm\node_modules\storj\node_modules\storj-lib\lib\bridge-client index.js file

**Comment by MeijeSibbel** [comment]
This was working with the previous core release.

**Comment by aleitner** [comment]
the cli fills in uri. Use the environment variable STORJ_BRIDGE or use the --url option
