### ISSUE TITLE
Feature: Allow Core-CLI terminal output to be logged to a .log file

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core-cli#28]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@0.6.5 /home/gordon/Code/storj-bridge
└── storj@0.6.5  -> /home/gordon/Code/storj-core
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Currently under windows one has to add  ``` `>>  path` ``` in order to log the Core-CLI output to a file. By adding a option like ` -log path_to_log_file ` , the CLI will create a log file in the specified file path containing the CLI output. This feature can be handy to monitor errors, upload states...  An extra option could be added to continuously redirect the core-CLI output only to the log file (>> under windows), meaning that no info will be displayed in the terminal window. This has some large benefits to those of us who not only want to monitor the continuous progress of the CLI, but who also want to be able to look back in time of the Core-CLI activity. If this is not a good idea then please close the issue.

### Actual Behavior

The only way to log the CLI output is by using > or >> under windows.

### Steps to Reproduce

**Comment by bookchin** [comment]
Let's not reinvent POSIX. You can monitor and write to a file with:

```
storj [options] [command] >> logfile | tail -f
```
