### ISSUE TITLE
Syntax is wrong for recursive uploads

### ISSUE THREAD

**Issue by jduerstock** [Storj/core-cli#5]
Line 214 reads of bin/storj.js incorrectly states:

``` 
'  or upload recursively using "/path/**/*".\n' +
```

it should read:

``` 
'  or upload recursively using "/path/*/*".\n' +
```

**Comment by jduerstock** [comment]
Why did this get flagged as an enhancement?  The syntax for recursive uploads is incorrect and will not function as currently written.  This is a bug, not an enhancement.

**Comment by aleitner** [comment]
Glob recursive file syntax is /**/*
