### ISSUE TITLE
Performance problem duplicate audit generation

### ISSUE THREAD

**Issue by littleskunk** [Storj/core-cli#6]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/usr/local/lib                                             
└── storj-cli@1.0.1
```

Replace the values below using the output from `node --version`.

```
v4.5.0
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
For each shard I would expect not more than one audit generation. 
Even if the upload failed I would expect a new contract with the same hash and the same audit. 
No need to  generate the same audit again.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
 [Mon Sep 26 2016 09:54:13 GMT+0200 (CEST)] [info]   Shard transfer failed 3 times, getting another contract...
[Mon Sep 26 2016 09:54:13 GMT+0200 (CEST)] [info]   Hash for this shard is: 4e8762dde7ff13d9b1d763d9eff0a5bb1503945d
[Mon Sep 26 2016 09:55:26 GMT+0200 (CEST)] [info]   Audit generation for shard done.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. ... Upload a 1GB file and wait for failed uploads
2. ... New audit generation?

**Comment by bookchin** [comment]
If I'm not mistaken, while the logging says new audit is generated, it actually does reuse the editing generated audit challenges and contract.

**Comment by littleskunk** [comment]
Audit generation needs 01:13. That doesn't look like a reuse.
