### ISSUE TITLE
Dev Request - Download unencrypted files, see explanation...

### ISSUE THREAD

**Issue by tempestb** [Storj/core-cli#70]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
-- storj@4.0.1
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

  Here is an outline of what I'm doing.  Right now, I am uploading files via a web utility I've created in ASP.NET and C#.   This appears to work fine.  

I then attempt to download those files with the CLI utility.  When I download the files, the CLI complains that the encryption key is not found in the keyring.  This is expected, and is fine.  (I do not know if this is fine for the CLI, but it is fine for my needs.  I do not need the CLI to decrypt the file, just download it.)   

The CLI then begins downloading the file.  It does this and reports for every 131072 bytes that it downloads.  It then stops and returns to the command line.  No errors are reported.  If I add up the 131072 byte sections, they match the size of the uploaded file, which is great.

But here is the problem.  The file that is downloaded is 0 bytes, and it is still "in use".  

So I am making a guess here, but I think that the CLI did not close gracefully, and possibly broke when it went to decrypt and wasn't able to.  (Although no error was thrown.)  This then left the connections open, and incomplete.

It may or may-not have anything to do with encryption.  The main problem is just that the connections are still open when it finishes.  

It would be beneficial for devs like me, to be able to download files with the CLI without decrypting and having the CLI close the connections properly, so I can compare my input / output locally vs what is on the web application.  So this is more of a request than a bug.

Don't waste your time on it if it is a hassle.  I just thought if you were ever in that piece of code and had to touch it anyway, you could investigate why the connections aren't closing there.  Thank You.

**Comment by littleskunk** [comment]
Missing timeout in core. I have the same problems even if the key exists and I get random freeze on file uploads as well.

Timeout is missing here:
https://github.com/Storj/core/blob/fc7877eced9022df403b94727bac2fe46456c4d6/lib/bridge-client/index.js#L766-L769

Pull request will follow. First I will test is on my branch.

**Comment by littleskunk** [comment]
Default timeout (20 sec) is to low. I don't get freeze anymore but increased failures. 50% failure rate it to high. Without timeout I had only 10%. I will increase the timeout and run some more tests.

**Comment by littleskunk** [comment]
30 sec timeout is stable. No freeze and same failure rate as usual.
