### ISSUE TITLE
[FEATURE] Add Own temp directory option

### ISSUE THREAD

**Issue by lakewik** [Storj/core-cli#74]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
/home/lakewik/.nvm/versions/node/v4.4.4/lib
└── storj@4.0.1 
```

Replace the values below using the output from `node --version`.

```
v4.4.4
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
I should can set the temp files directory for files uploading. Example situation: I'm uploading on RaspberryPi files from connected external HDD. The temporary files (file divided to smaller shards) is stored on (very slow) SD card. I would like to store it on this external HDD. Example option: --tmpdir = /path/to/tmp/dir 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
I don't see this option.
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

Don't requried

**Comment by bookchin** [comment]
Use `STORJ_TEMP`: https://storj.github.io/core/tutorial-environment-variables.html
