### ISSUE TITLE
feature: debug warning when nodes are blacklisted

### ISSUE THREAD

**Issue by braydonf** [Storj/core-cli#80]
When debugging code during development, it's possible to introduce a bug, and then put development nodes into a blacklist. With debug enabled, it could be useful to log the fact that nodes are being blacklisted. It can be quite confusing to debug this, as the error message indicates that the contract is no longer open to offers, which is also not logged, and requires some digging.

**Comment by littleskunk** [comment]
Are you sure this is a core-cli issue? 'contract is no longer open to offers' is never displayed on CLI. This message belongs to core, storjshare-cli and storjshare-gui.
