### ISSUE TITLE
Download hangs + wrong received data amount indication

### ISSUE THREAD

**Issue by MeijeSibbel** [Storj/core-cli#92]
### Package Versions

Replace the values below using the output from `npm list storj`. Use ```npm list -g storj``` if installed globally.

```
storj-bridge@4.3.2 /home/gordon/Code/storj-bridge
└── Storjcli: 4.0.0 | Core: 6.0.15

OS: windows 10
```

Replace the values below using the output from `node --version`.

```
v6.9.1
```

### Expected Behavior

Please describe the program's expected behavior. Include an example of your
usage code in the back ticks below if applicable.

```
1- Download does not hang.
2-  The info message on downloaded data amount moves at the same speed as the actual download speed (not the case). 
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
1- The download hangs: https://youtu.be/M7aQUxwOZcg
2- It appears that the info messages of received data amount are not synchronized with the actual amount of downloaded data. Towards the end of the download these messages suddenly appear at a much faster rate while almost nothing is being downloaded. So either there is a lag between what is displayed and what has been downloaded or the info messages are incorrect. 
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Download a file (2GB).
2. ...
3. ...

**Comment by MeijeSibbel** [comment]
https://youtu.be/MxvcnwLp6Qc

**Comment by bookchin** [comment]
Shards are downloaded with a degree of parallelism and buffered, but are read from the remote or buffer and written sequentially. this is why the speed appears to increase after a certain amount of time - the rest of the shards are being read from the buffer

**Comment by MeijeSibbel** [comment]
@bookchin , the hanging appears to be the result of the bridge limiting code that cuts off my download mid-way, which causes it to hang/ stop downloading. So it's not a bug. I will close the issue.
